apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web_server
  name: test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: http
        name: http
